services:
  - type: web
    name: rag-system-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run StreamlitApp.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    region: frankfurt
